### ISSUE TITLE
Errors running $ bundle exec knife solo bootstrap root@YOURSERVERIP

### ISSUE THREAD

**Issue by ziazek** [TalkingQuickly/rails-server-template#26]
When running 
```
$ bundle exec knife solo bootstrap root@YOURSERVERIP
```
it results in a couple of errors before saying it failed.
```
Recipe: locales::install
  * execute[locale-gen] action nothing (skipped due to action :nothing)
  * ruby_block[add locale en_US] action run

    ================================================================================
    Error executing action `run` on resource 'ruby_block[add locale en_US]'
    ================================================================================

    ArgumentError
    -------------
    File '/var/lib/locales/supported.d/local' does not exist

    Cookbook Trace:
    ---------------
    /root/chef-solo/cookbooks-2/locales/providers/default.rb:79:in `new'
    /root/chef-solo/cookbooks-2/locales/providers/default.rb:79:in `block (2 levels) in add_locale'

    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks-2/locales/providers/default.rb

     77:   ruby_block "add locale #{locale}" do
     78:     block do
     79:       file = Chef::Util::FileEdit.new(node['locales']['locale_file'])
     80:       line = "#{high_locale(locale)} #{new_resource.charmap}"
     81:       file.insert_line_if_no_match(/^#{line}$/, line)
     82:       file.write_file
     83:     end
     84:     notifies :run, 'execute[locale-gen]', :immediate
     85:   end
     86: end

    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks-2/locales/providers/default.rb:77:in `add_locale'

    ruby_block("add locale en_US") do
      action "run"
      retries 0
      retry_delay 2
      guard_interpreter :default
      block_name "add locale en_US"
      cookbook_name :locales
      block #<Proc:0x0000000279aef8@/root/chef-solo/cookbooks-2/locales/providers/default.rb:78>
    end

Recipe: ntp::apparmor
  * service[apparmor] action restart

    ================================================================================
    Error executing action `restart` on resource 'service[apparmor]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - /etc/init.d/apparmor stop

    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks-2/ntp/recipes/apparmor.rb

     20: service 'apparmor' do
     21:   action :nothing
     22: end
     23:

    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks-2/ntp/recipes/apparmor.rb:20:in `from_file'

    service("apparmor") do
      action [:nothing]
      supports {:restart=>false, :reload=>false, :status=>false}
      retries 0
      retry_delay 2
      guard_interpreter :default
      service_name "apparmor"
      pattern "apparmor"
      cookbook_name :ntp
      recipe_name "apparmor"
    end

Recipe: ntp::default
  * service[ntp] action restart
    - restart service service[ntp]

Running handlers:
[2015-01-28T08:51:04+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-01-28T08:51:04+00:00] ERROR: Exception handlers complete
[2015-01-28T08:51:04+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 25 resources updated in 55.758383974 seconds
[2015-01-28T08:51:04+00:00] ERROR: Chef::Exceptions::MultipleFailures
[2015-01-28T08:51:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

**Comment by ziazek** [comment]
I've realised the mistake I made; on DigitalOcean do **NOT** select any application! 
![dont-do-this](https://cloud.githubusercontent.com/assets/505254/5987567/aef2714a-a96d-11e4-8fbb-7df3f8528b1f.png)
