### ISSUE TITLE
Provisioning fails with an error

### ISSUE THREAD

**Issue by danielristic** [TalkingQuickly/rails-server-template#39]
I've already used the tools provided here to provision multiple servers in the past but as I've started fresh on a new machine, I can't seem to get it through, it always stops with an error.

I'm on OS X El Capitain, running the latest chef-dk:

```
chef -v
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

I'm trying to provision a DO droplet running Ubuntu 14.04.3 LTS, using the standard config file from the repository named rails-postgres-redis-1. Here's the output I get after performing a `bundle exec knife solo bootstrap`:

```
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
Bootstrapping Chef...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18736  100 18736    0     0  38524      0 --:--:-- --:--:-- --:--:-- 38472
Downloading Chef 11.16.4 for ubuntu...
downloading https://www.opscode.com/chef/metadata?v=11.16.4&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
  to file /tmp/install.sh.6349/metadata.txt
trying wget...
url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_11.16.4-1_amd64.deb
md5	a9965ce5811ddd75af1b587e40cca934
sha256	0b98b310afc2c0b066648e550e7b59a5e39faf60dc4fd9b4792035d0553c27c3
downloaded metadata file looks valid...
downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_11.16.4-1_amd64.deb
  to file /tmp/install.sh.6349/chef_11.16.4-1_amd64.deb
trying wget...
Comparing checksum with sha256sum...
Installing Chef 11.16.4
installing with dpkg...
(Reading database ... 98865 files and directories currently installed.)
Preparing to unpack .../chef_11.16.4-1_amd64.deb ...
Unpacking chef (11.16.4-1) over (11.16.4-1) ...
Setting up chef (11.16.4-1) ...
Thank you for installing Chef!
Running Chef on 46.101.62.17...
Installing Berkshelf cookbooks to 'cookbooks'...
Resolving cookbook dependencies...
Fetching 'rbenv' from git://github.com/fnichol/chef-rbenv.git (at master)
ERROR: Berkshelf::MismatchedCookbookName: Berkshelf::MismatchedCookbookName

```

Then I tried to replace the name of the cookbook in the `Berksfile` from 'rbenv' to 'ruby_rbenv' and then it went past dependency resolving but then failed later with:

```
Starting Chef Client, version 11.16.4
Compiling Cookbooks...

Running handlers:
[2015-10-14T12:20:28-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-10-14T12:20:28-04:00] ERROR: Exception handlers complete
[2015-10-14T12:20:28-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 0.966635992 seconds
[2015-10-14T12:20:28-04:00] ERROR: Cookbook rbenv not found. If you're loading rbenv from another cookbook, make sure you configure the dependency in your metadata
[2015-10-14T12:20:28-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

**Comment by TalkingQuickly** [comment]
I believe it relates to this; https://github.com/TalkingQuickly/rails-server-template/pull/38/files, haven't had a chance to test that PR yet, but if you need an immediate fix, that's likely to be it!

I'd also advise against ChefDK, if it's in $PATH ahead of rbenv/ rvm/ etc then you'll use its version, not the version specified in the Gemfile and so behaviour may be unpredictable

**Comment by danielristic** [comment]
Thanks, it got rid of the "rbenv not found" error but now I have this:

```
Starting Chef Client, version 11.16.4
Compiling Cookbooks...
[2015-10-14T12:46:39-04:00] WARN: encrypted_data_bag_Secret is set but file does not exist. Unsetting

================================================================================
Recipe Compile Error in /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb
================================================================================

NoMethodError
-------------
undefined method `provides' for Chef::Provider::FirewallFirewalld:Class

Cookbook Trace:
---------------
  /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb:22:in `<class:FirewallFirewalld>'
  /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb:19:in `<class:Chef>'
  /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb:18:in `<top (required)>'

Relevant File Content:
----------------------
/root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb:

 15:  # See the License for the specific language governing permissions and
 16:  # limitations under the License.
 17:  #
 18:  class Chef
 19:    class Provider::FirewallFirewalld < Chef::Provider::LWRPBase
 20:      include FirewallCookbook::Helpers::Firewalld
 21:  
 22>>     provides :firewall, os: 'linux', platform_family: %w(rhel fedora) do |node|
 23:        node['platform_version'].to_f >= 7.0
 24:      end
 25:  
 26:      def whyrun_supported?
 27:        false
 28:      end
 29:  
 30:      action :install do
 31:        next if disabled?(new_resource)


Running handlers:
[2015-10-14T12:46:39-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-10-14T12:46:39-04:00] ERROR: Exception handlers complete
[2015-10-14T12:46:39-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 7.990592767 seconds
[2015-10-14T12:46:40-04:00] ERROR: undefined method `provides' for Chef::Provider::FirewallFirewalld:Class
[2015-10-14T12:46:40-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

**Comment by TalkingQuickly** [comment]
You're the second person who this has happened to but I can't for the life of me recreate it (https://github.com/TalkingQuickly/rails-server-template/issues/37)!

Could you send me the output of:

`bundle exec chef-client -v`
and
`echo $PATH`

Only immediate difference I can see to my version is that it looks like you're using chef 11.16.4 instead of 11.16.0 which is specified in the Gemfile. Which implies ChefDK is overriding (is earlier in $PATH)

**Comment by danielristic** [comment]
You were right about ChefDK overriding the PATH so I removed it altogether to use the gem instead, but I'm still getting the same error.

The output of `bundle exec chef-client -v` is:
```
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
/Users/daniel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/chef-11.16.4/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
Chef: 11.16.4
```

And the output of `echo $PATH` is:
```
/Users/daniel/.rbenv/shims:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/share/npm/bin:/usr/local/bin:/Library/PostgreSQL/9.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/mysql/bin
```

As it was still using the version `11.16.4` I checked the Gemfile and it read `gem 'chef', '~> 11.16.0'` so I replaced it with `gem 'chef', '11.16.0'` to force the use of version `11.16.0`, ran `bundle update chef` and tried again but I still get the same error:

```
Starting Chef Client, version 11.16.0
Compiling Cookbooks...
[2015-10-14T14:08:42-04:00] WARN: encrypted_data_bag_Secret is set but file does not exist. Unsetting

================================================================================
Recipe Compile Error in /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb
================================================================================

NoMethodError
-------------
undefined method `provides' for Chef::Provider::FirewallFirewalld:Class

Cookbook Trace:
---------------
  /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb:22:in `<class:FirewallFirewalld>'
  /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb:19:in `<class:Chef>'
  /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb:18:in `<top (required)>'

Relevant File Content:
----------------------
/root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_firewalld.rb:

 15:  # See the License for the specific language governing permissions and
 16:  # limitations under the License.
 17:  #
 18:  class Chef
 19:    class Provider::FirewallFirewalld < Chef::Provider::LWRPBase
 20:      include FirewallCookbook::Helpers::Firewalld
 21:  
 22>>     provides :firewall, os: 'linux', platform_family: %w(rhel fedora) do |node|
 23:        node['platform_version'].to_f >= 7.0
 24:      end
 25:  
 26:      def whyrun_supported?
 27:        false
 28:      end
 29:  
 30:      action :install do
 31:        next if disabled?(new_resource)


Running handlers:
[2015-10-14T14:08:43-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-10-14T14:08:43-04:00] ERROR: Exception handlers complete
[2015-10-14T14:08:43-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 12.033161307 seconds
[2015-10-14T14:08:43-04:00] ERROR: undefined method `provides' for Chef::Provider::FirewallFirewalld:Class
[2015-10-14T14:08:43-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

**Comment by danielristic** [comment]
I've realized that the problem was due to wrong version of the cookbooks being used, must have done a `bundle exec berks update` that messed things up at some point.

Cloning a fresh version of the repository and doing `bundle exec berks install` solved the issue.
