### ISSUE TITLE
Trying to install mysql 5.6 fails with an error

### ISSUE THREAD

**Issue by danielristic** [TalkingQuickly/rails-server-template#50]
The default configuration for role[mysql-server] installs versions 5.5 of mysql.

When trying to install version 5.6 instead, using the following confguration:

``` json
{
  "environment":"production",
  [...]
  "mysql" : {
    "version" : "5.6",
    "server_root_password" : "XXXX",
    "server_debian_password" : "XXXX",
    "server_repl_password":"XXXX"
  },
  "run_list":
  [
    "role[server]",
    "role[mysql-server]"
  ]
}
```

It fails with the following error:

``` bash
* package[mysql-server-5.6] action install

      ================================================================================
      Error executing action `install` on resource 'package[mysql-server-5.6]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '100'
      ---- Begin output of apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 ----
      STDOUT: Reading package lists...
      Building dependency tree...
      Reading state information...
      Some packages could not be installed. This may mean that you have
      requested an impossible situation or if you are using the unstable
      distribution that some required packages have not yet been created
      or been moved out of Incoming.
      The following information may help to resolve the situation:

      The following packages have unmet dependencies:
       mysql-server-5.6 : Depends: mysql-client-5.6 (>= 5.6.30-0ubuntu0.14.04.1) but it is not going to be installed
      STDERR: E: Unable to correct problems, you have held broken packages.
      ---- End output of apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 ----
      Ran apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 returned 100

      Resource Declaration:
      ---------------------
      # In /root/chef-solo/cookbooks-2/mysql/libraries/provider_mysql_service_ubuntu.rb

       54:             package new_resource.package_name do
       55:               action :install
       56:             end
       57: 

      Compiled Resource:
      ------------------
      # Declared in /root/chef-solo/cookbooks-2/mysql/libraries/provider_mysql_service_ubuntu.rb:54:in `block (2 levels) in <class:Ubuntu>'

      package("mysql-server-5.6") do
        action [:install]
        retries 0
        retry_delay 2
        guard_interpreter :default
        package_name "mysql-server-5.6"
        version "5.6.30-0ubuntu0.14.04.1"
        timeout 900
        cookbook_name :mysql
      end


    ================================================================================
    Error executing action `create` on resource 'mysql_service[default]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    package[mysql-server-5.6] (/root/chef-solo/cookbooks-2/mysql/libraries/provider_mysql_service_ubuntu.rb line 54) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
    ---- Begin output of apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 ----
    STDOUT: Reading package lists...
    Building dependency tree...
    Reading state information...
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     mysql-server-5.6 : Depends: mysql-client-5.6 (>= 5.6.30-0ubuntu0.14.04.1) but it is not going to be installed
    STDERR: E: Unable to correct problems, you have held broken packages.
    ---- End output of apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 ----
    Ran apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 returned 100

    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks-2/mysql/recipes/server.rb

     20: mysql_service node['mysql']['service_name'] do
     21:   version node['mysql']['version']
     22:   port node['mysql']['port']
     23:   data_dir node['mysql']['data_dir']
     24:   server_root_password node['mysql']['server_root_password']
     25:   server_debian_password node['mysql']['server_debian_password']
     26:   server_repl_password node['mysql']['server_repl_password']
     27:   allow_remote_root node['mysql']['allow_remote_root']
     28:   remove_anonymous_users node['mysql']['remove_anonymous_users']
     29:   remove_test_database node['mysql']['remove_test_database']
     30:   root_network_acl node['mysql']['root_network_acl']
     31:   version node['mysql']['version']
     32:   action :create
     33: end

    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks-2/mysql/recipes/server.rb:20:in `from_file'

    mysql_service("default") do
      action [:create]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      guard_interpreter :default
      service_name "default"
      version "5.6"
      package_name "mysql-server-5.6"
      data_dir "/var/lib/mysql"
      port "3306"
      remove_anonymous_users true
      remove_test_database true
      server_root_password "XXXX"
      server_debian_password "XXXX"
      server_repl_password "XXXX"
      cookbook_name :mysql
      recipe_name "server"
    end

Recipe: ntp::default
  * service[ntp] action restart
    - restart service service[ntp]
Recipe: ntp::apparmor
  * service[apparmor] action restart
    - restart service service[apparmor]
Recipe: fail2ban::default
  * service[fail2ban] action restart
    - restart service service[fail2ban]

Running handlers:
[2016-05-09T11:46:06-04:00] ERROR: Running exception handlers
Running handlers complete
[2016-05-09T11:46:06-04:00] ERROR: Exception handlers complete
[2016-05-09T11:46:06-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 60 resources updated in 105.953004807 seconds
[2016-05-09T11:46:06-04:00] ERROR: mysql_service[default] (mysql::server line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: package[mysql-server-5.6] (/root/chef-solo/cookbooks-2/mysql/libraries/provider_mysql_service_ubuntu.rb line 54) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mysql-server-5.6 : Depends: mysql-client-5.6 (>= 5.6.30-0ubuntu0.14.04.1) but it is not going to be installed
STDERR: E: Unable to correct problems, you have held broken packages.
---- End output of apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 ----
Ran apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 returned 100
[2016-05-09T11:46:06-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

**Comment by theonedemon** [comment]
bump

**Comment by TalkingQuickly** [comment]
The configuration in older versions of the book is no longer compatible with the mysql cookbook; https://github.com/chef-cookbooks/mysql my understanding is that the new approach taken by that cookbook is to require a wrapper cookbook.

**Comment by danielristic** [comment]
Thanks! I would be very interested in a blog post on that topic as many people still use MySQL for their databases, especially in production.
