### ISSUE TITLE
Error, not sure how to proceed

### ISSUE THREAD

**Issue by rubygeek** [TalkingQuickly/rails-server-template#60]
Following along with the book, after getting past the issue with [nginix](https://github.com/TalkingQuickly/rails-server-template/pull/54) I merrily go a few more steps only to be stopped by this:

advise on how to fix? 

```
192.168.56.101     - re-run ohai and merge results into node attributes
192.168.56.101
192.168.56.101   ================================================================================
192.168.56.101   Recipe Compile Error in /var/chef/cache/cookbooks/postgresql/recipes/server.rb
192.168.56.101   ================================================================================
192.168.56.101
192.168.56.101   RuntimeError
192.168.56.101   ------------
192.168.56.101   Not supported release by PGDG apt repository
192.168.56.101
192.168.56.101   Cookbook Trace:
192.168.56.101   ---------------
192.168.56.101     /var/chef/cache/cookbooks/postgresql/recipes/apt_pgdg_postgresql.rb:2:in `from_file'
192.168.56.101     /var/chef/cache/cookbooks/postgresql/recipes/client.rb:27:in `from_file'
192.168.56.101     /var/chef/cache/cookbooks/postgresql/recipes/server.rb:22:in `from_file'
192.168.56.101
192.168.56.101   Relevant File Content:
192.168.56.101   ----------------------
192.168.56.101   /var/chef/cache/cookbooks/postgresql/recipes/apt_pgdg_postgresql.rb:
192.168.56.101
192.168.56.101     1:  if not %w(jessie squeeze wheezy sid lucid precise saucy trusty utopic wily xenial).include? node['postgresql']['pgdg']['release_apt_codename']
192.168.56.101     2>>   raise "Not supported release by PGDG apt repository"
192.168.56.101     3:  end
192.168.56.101     4:
192.168.56.101     5:  include_recipe 'apt'
192.168.56.101     6:
192.168.56.101     7:  file "remove deprecated Pitti PPA apt repository" do
192.168.56.101     8:    action :delete
192.168.56.101     9:    path "/etc/apt/sources.list.d/pitti-postgresql-ppa"
192.168.56.101    10:  end
192.168.56.101    11:
192.168.56.101
192.168.56.101   System Info:
192.168.56.101   ------------
192.168.56.101   chef_version=12.21.3
192.168.56.101   platform=ubuntu
192.168.56.101   platform_version=17.04
192.168.56.101   ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
192.168.56.101   program_name=chef-client worker: ppid=8565;start=20:03:50;
192.168.56.101   executable=/opt/chef/bin/chef-client
192.168.56.101
``

**Comment by rubygeek** [comment]
Found out error is from the version of ubuntu, I needed to use an older version  (ubuntu 16) so it worked with the postgresql cookbook.
