### ISSUE TITLE
Quick Start errors: provisioning instructions broken?

### ISSUE THREAD

**Issue by danielristic** [TalkingQuickly/rails-server-template#63]
I followed the updated instructions in the latest version of the book to provision a newly created VPS on Digital Ocean.

Everything works as expected until the final command `knife zero converge` where I get the following error:

```
NameError
---------
uninitialized constant Chef::Provider::LWRPBase::InlineResources
```

Here is the full console output:

```
Execute command hook in before_converge.
Resolving cookbook dependencies...
Fetching cookbook index from https://api.berkshelf.com...
Using 7-zip (1.0.2)
Using apt (2.9.2)
Using build-essential (2.4.0)
Using chef-sugar (3.3.0)
Using chef_handler (1.4.0)
Using compat_resource (12.10.6)
Using fail2ban (2.3.0)
Using firewall (2.5.2)
Using hostnames (0.3.1)
Using hostsfile (2.4.5)
Using iptables (2.2.0)
Using bluepill (2.4.3)
Using java (1.39.0)
Using locale (1.1.0)
Using memcached (3.0.0)
Using monit-tlq (0.3.11) from git://github.com/TalkingQuickly/monit-tlq.git (at master)
Using monit_configs-tlq (0.1.2) from git://github.com/TalkingQuickly/monit_configs-tlq.git (at master)
Using mysql (5.6.3)
Using nginx (2.7.6) from git://github.com/miketheman/nginx.git (at master)
Using ntp (2.0.0)
Using apt-chef (1.0.0)
Using ohai (2.1.0)
Using openssh (1.2.2)
Using openssl (4.4.0)
Using packagecloud (0.2.3)
Using postgresql (4.0.6)
Using rails_gem_dependencies-tlq (0.0.3) from git://github.com/TalkingQuickly/rails_gem_dependencies-tlq.git (at master)
Using redis-server (0.1.1) from git://github.com/TalkingQuickly/redis-server.git (at master)
Using rsyslog (4.0.0)
Using ruby_build (0.8.0)
Using ruby_rbenv (1.0.1) from git://github.com/fnichol/chef-rbenv.git (at master)
Using runit (1.7.8)
Using sudo (2.9.0)
Using ufw (1.0.0)
Using users (2.0.3) from git://github.com/opscode-cookbooks/users.git (at master)
Using windows (1.43.0)
Using yum (3.11.0)
Using yum-epel (0.7.0)
Using yum-mysql-community (0.2.0)

WARN: Starting local-mode server in deprecated socket mode (CHEF-18) at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/knife:25:in `<top (required)>'.
Please see https://docs.chef.io/deprecations_local_listen.html for further details and information on how to correct this problem.

Starting Chef Client, version 13.8.0
resolving cookbooks for run list: ["apt::default", "openssl::default", "build-essential::default", "users::sysadmins", "firewall::default", "ufw::default", "apt::unattended-upgrades", "ntp::default", "sudo::default", "locale::default", "fail2ban::default", "monit-tlq::default", "monit_configs-tlq::system", "nginx::repo", "nginx::default", "monit_configs-tlq::nginx", "postgresql::server", "monit_configs-tlq::postgres", "rails_gem_dependencies-tlq", "ruby_build", "ruby_rbenv::system", "redis-server::default", "monit_configs-tlq::redis-server"]

Synchronizing Cookbooks:
  - apt (2.9.2)
  - openssl (4.4.0)
  - build-essential (2.4.0)
  - users (2.0.3)
  - firewall (2.5.2)
  - ufw (1.0.0)
  - ntp (2.0.0)
  - sudo (2.9.0)
  - locale (1.1.0)
  - fail2ban (2.3.0)
  - monit-tlq (0.3.11)
  - monit_configs-tlq (0.1.2)
  - nginx (2.7.6)
  - rails_gem_dependencies-tlq (0.0.3)
  - postgresql (4.0.6)
  - ruby_build (0.8.0)
  - ruby_rbenv (1.0.1)
  - redis-server (0.1.1)
  - chef-sugar (3.3.0)
  - 7-zip (1.0.2)
  - windows (1.43.0)
  - yum-epel (0.7.0)
  - bluepill (2.4.3)
  - ohai (2.1.0)
  - runit (1.7.8)
  - chef_handler (1.4.0)
  - yum (3.11.0)
  - rsyslog (4.0.0)
  - packagecloud (0.2.3)
  - compat_resource (12.10.6)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb
================================================================================

NameError
---------
uninitialized constant Chef::Provider::LWRPBase::InlineResources

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/provider.rb:6:in `<class:Provider>'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/provider.rb:4:in `<top (required)>'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches.rb:6:in `<top (required)>'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/resource.rb:1:in `<top (required)>'
  /var/chef/cache/cookbooks/compat_resource/files/lib/compat_resource.rb:7:in `<top (required)>'
  /var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb:24:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/provider.rb:

  1:  require 'chef/provider'
  2:  require 'chef/provider/lwrp_base'
  3:  
  4:  class Chef::Provider
  5:    if !defined?(InlineResources)
  6>>     InlineResources = Chef::Provider::LWRPBase::InlineResources
  7:    end
  8:    module InlineResources
  9:      require 'chef/dsl/recipe'
 10:      require 'chef/dsl/platform_introspection'
 11:      require 'chef/dsl/data_query'
 12:      require 'chef/dsl/include_recipe'
 13:      include Chef::DSL::Recipe
 14:      include Chef::DSL::PlatformIntrospection
 15:      include Chef::DSL::DataQuery

System Info:
------------
chef_version=13.8.0
platform=ubuntu
platform_version=16.04
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
program_name=chef-client worker: ppid=2119;start=15:31:29;
executable=/opt/chef/bin/chef-client

Running handlers:
[2018-02-27T15:32:49+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-02-27T15:32:49+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 minutes 20 seconds
[2018-02-27T15:32:49+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-02-27T15:32:49+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
159.65.23.8 [2018-02-27T15:32:49+00:00] ERROR: uninitialized constant Chef::Provider::LWRPBase::InlineResources
159.65.23.8 [2018-02-27T15:32:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

And the Chef stacktrace:

```
NameError: uninitialized constant Chef::Provider::LWRPBase::InlineResources
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/provider.rb:6:in `<class:Provider>'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/provider.rb:4:in `<top (required)>'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches.rb:6:in `<top (required)>'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/resource.rb:1:in `<top (required)>'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/chef/cache/cookbooks/compat_resource/files/lib/compat_resource.rb:7:in `<top (required)>'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/chef/cache/cookbooks/compat_resource/libraries/autoload.rb:24:in `<top (required)>'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context/cookbook_compiler.rb:224:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context/cookbook_compiler.rb:224:in `block in load_libraries_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context/cookbook_compiler.rb:220:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context/cookbook_compiler.rb:220:in `load_libraries_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context/cookbook_compiler.rb:101:in `block in compile_libraries'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context/cookbook_compiler.rb:100:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context/cookbook_compiler.rb:100:in `compile_libraries'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/run_context.rb:191:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application.rb:292:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application.rb:280:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application.rb:280:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application.rb:245:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application.rb:233:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application/client.rb:457:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:59:in `load'
/usr/bin/chef-client:59:in `<main>'
```

**Comment by danielristic** [comment]
I got it working, it was a dependency issue and a few cookbooks needed to be updated.

In case anyone else needs it, here are the modifications of the Berksfile that worked for me:

```
cookbook 'ufw', '~> 2.0.0'
cookbook 'firewall', '~> 2.6.2'

cookbook 'nginx'

cookbook 'users', '~> 4.0.3'

cookbook 'ruby_rbenv', '~> 1.2.1'
```

After these changes are saved, simply run `berks update` and then you can follow the instructions from the Quick Start chapter of the book.

**Comment by danielristic** [comment]
After more tweaking around I noticed that the code provided in this repository works as expected, provided that you don't use a too recent version of Chef: in the chapter "Installing Tools", if you install the most recent ChefDK it will show the errors above, but if you install a version that packs Chef 12 (1.6.11 of the developement kit is the most recent one that has Chef 12), it will work without the need to update some cookbooks.

**Comment by TalkingQuickly** [comment]
Hey @danielristic really appreciate all the comments on these issues, you were spot on with why it was failing. In the next edition of the book the plan is to a) have weekly recurring CI to catch these failures earlier and b) to do a better job of pinning tools etc to a specific version. If you're still provisioning servers like this I'd love your take on the next edition!

**Comment by danielristic** [comment]
Hi @TalkingQuickly, glad to see new activity on this repo! I still provision servers with this and your book is hands down the best ressource on production-grade rails apps deployment available. I'll be happy to check out the new edition!

I haven't had the chance to try v5.0 yet but I noticed that you dropped the mysql-server role (which even had its own chapter on an earlier version of the book). I use that too as I have a couple of apps using mysql and I got it to work on 16.06 (which required a bit of tinkering as the mysql cookbook has changed a lot). I might try to make it work on 20.04 too.

**Comment by TalkingQuickly** [comment]
Hey, thanks for the kind words @danielristic as soon as the first draft of the new edition is available, I'll send it across! I only dropped the MySQL role because it's been quite a while since I used MySQL in production so my expertise might be a bit thin there now, but would be awesome to re-add it to the repo if there's a solid production config you get working!
